// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[category]" | "/[category]/[subcategory]" | "/admin" | "/cart" | "/checkout" | "/checkout/delivery" | "/checkout/payment" | "/checkout/review" | "/checkout/success" | "/login" | "/new-in" | "/orders" | "/orders/[orderId]" | "/product/[slug]" | "/register" | "/search" | "/wishlist"
type AppRouteHandlerRoutes = "/api/search-suggestions"
type PageRoutes = never
type LayoutRoutes = "/" | "/cart" | "/checkout" | "/orders" | "/orders/[orderId]" | "/wishlist"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[category]": { "category": string; }
  "/[category]/[subcategory]": { "category": string; "subcategory": string; }
  "/admin": {}
  "/api/search-suggestions": {}
  "/cart": {}
  "/checkout": {}
  "/checkout/delivery": {}
  "/checkout/payment": {}
  "/checkout/review": {}
  "/checkout/success": {}
  "/login": {}
  "/new-in": {}
  "/orders": {}
  "/orders/[orderId]": { "orderId": string; }
  "/product/[slug]": { "slug": string; }
  "/register": {}
  "/search": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/cart": never
  "/checkout": never
  "/orders": never
  "/orders/[orderId]": never
  "/wishlist": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
